import turtle

screen = turtle.Screen()
screen.screensize(800,800)
screen.bgcolor('peru')
t_ground = turtle.Turtle()
jimmy = turtle.Turtle()
jimmy.speed(0)

t_ground.penup()
t_ground.pencolor('saddlebrown')
t_ground.fillcolor('saddlebrown')
t_ground.speed(0)
t_ground.goto(-1000,-100)
t_ground.pendown()
t_ground.begin_fill()
t_ground.goto(1000,-100)
t_ground.goto(1000,-100)
t_ground.goto(1000,-1000)
t_ground.goto(-1000,-1000)
t_ground.goto(-1000,-100)
t_ground.end_fill()

# window
jimmy.penup()
jimmy.goto(-200,100)
jimmy.pendown()
jimmy.pencolor('lightsteelblue')
jimmy.fillcolor('lightsteelblue')
jimmy.begin_fill()
jimmy.forward(150)
jimmy.left(90)
jimmy.forward(150)
jimmy.left(90)
jimmy.forward(150)
jimmy.left(90)
jimmy.forward(150)
jimmy.end_fill()

jimmy.penup()
jimmy.goto(-200,100)
jimmy.pensize(3)
jimmy.pendown()
jimmy.pencolor('snow')
jimmy.forward(-150)
jimmy.right(90)
jimmy.forward(-150)
jimmy.right(90)
jimmy.forward(-150)
jimmy.right(90)
jimmy.forward(-150)

jimmy.penup()
jimmy.goto(-120,100)
jimmy.pendown()
jimmy.pensize(5)
jimmy.left(90)
jimmy.forward(150)

jimmy.penup()
jimmy.goto(-200,170)
jimmy.pendown()
jimmy.pensize(5)
jimmy.right(90)
jimmy.forward(150)
jimmy.penup()

# stump
jimmy.pencolor('saddlebrown')
jimmy.fillcolor('saddlebrown')
jimmy.goto(-250,200)
jimmy.pendown()
jimmy.pensize(10)
jimmy.right(90)
jimmy.forward(300)
jimmy.end_fill()
jimmy.penup()

# tree
jimmy.pencolor('forestgreen')
jimmy.fillcolor('forestgreen')
jimmy.pensize()
jimmy.begin_fill()
jimmy.goto(-250.0,200.0)
jimmy.pendown()
jimmy.goto(-300.0,-80)
jimmy.goto(-200,-80)
jimmy.goto(-250.0,200.0)
jimmy.end_fill()
jimmy.penup()

# gift
jimmy.goto(-170,-100)
jimmy.left(90)
jimmy.fillcolor('green')
jimmy.pencolor('forestgreen')
jimmy.pendown()
jimmy.begin_fill()
jimmy.forward(20)
jimmy.left(90)
jimmy.forward(30)
jimmy.left(90)
jimmy.forward(30)
jimmy.left(90)
jimmy.forward(30)
jimmy.left(90)
jimmy.forward(30)
jimmy.end_fill()
jimmy.penup()

# table
jimmy.goto(-100,-200)
jimmy.pencolor("sienna")
jimmy.fillcolor('sienna')
jimmy.begin_fill()
jimmy.pendown()
jimmy.circle(50)
jimmy.end_fill()
jimmy.penup()

jimmy.goto(-140,-170)
jimmy.right(90)
jimmy.pendown()
jimmy.forward(50)
jimmy.penup()

jimmy.goto(-60,-170)
jimmy.pendown()
jimmy.forward(50)
jimmy.penup()

# cookies
jimmy.goto(-90,-160)
jimmy.pencolor('white')
jimmy.fillcolor('white')
jimmy.pendown()
jimmy.begin_fill()
jimmy.circle(15)
jimmy.end_fill()

jimmy.penup()
jimmy.pencolor('sienna2')
jimmy.fillcolor('sienna2')
jimmy.goto(-90,-160)
jimmy.pensize(1)
jimmy.pendown()
jimmy.begin_fill()
jimmy.circle(10)
jimmy.end_fill()
jimmy.penup()

# letter
jimmy.goto(-100,-120)
jimmy.fillcolor('white')
jimmy.pencolor('white')
jimmy.pendown()
jimmy.begin_fill()
jimmy.left(90)
jimmy.forward(20)
jimmy.left(90)
jimmy.forward(30)
jimmy.left(90)
jimmy.forward(40)
jimmy.left(90)
jimmy.forward(30)
jimmy.left(90)
jimmy.forward(20)
jimmy.end_fill()

jimmy.goto(-118,-110)
jimmy.pencolor('red')
jimmy.write("Santa",font=('Times New Roman',10,'bold italic'))
jimmy.penup()

# milk
jimmy.goto(-120,-140)
jimmy.pencolor('white')
jimmy.fillcolor('white')
jimmy.pendown()
jimmy.begin_fill()
jimmy.right(90)
jimmy.forward(20)
jimmy.right(90)
jimmy.forward(20)
jimmy.right(90)
jimmy.forward(20)
print(jimmy.xcor())
print(jimmy.ycor())
jimmy.right(90)
jimmy.forward(20)
jimmy.end_fill()
jimmy.penup()

jimmy.goto(-139.99999999999997,-119)
jimmy.pencolor('gray')
jimmy.pensize(3)
jimmy.pendown()
jimmy.right(90)
jimmy.forward(40)
jimmy.left(90)
jimmy.forward(20)
jimmy.left(90)
jimmy.forward(40)

# last line
turtle.done()